name: 'External PR Docker Build'

on:
  pull_request:
    types:
      - 'synchronize'
      - 'opened'

env:
  environment: CIENV
  PR_NUMBER: ${{ github.event.pull_request.number }}
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

jobs:
   docker:
    if: github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ixsystems/truenas-webui:${{ env.PR_NUMBER }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
